config/routes.rb
Rails.application.routes.draw do
  resources :sextos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sexto.rb
class Sexto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sextos_controller.rb
class SextosController < ApplicationController
  before_action :set_sexto, only: [:show, :edit, :update, :destroy]

  # GET /sextos
  # GET /sextos.json
  def index
    @sextos = Sexto.all
  end

  # GET /sextos/1
  # GET /sextos/1.json
  def show
  end

  # GET /sextos/new
  def new
    @sexto = Sexto.new
  end

  # GET /sextos/1/edit
  def edit
  end

  # POST /sextos
  # POST /sextos.json
  def create
    @sexto = Sexto.new(sexto_params)

    respond_to do |format|
      if @sexto.save
        format.html { redirect_to @sexto, notice: 'Sexto was successfully created.' }
        format.json { render :show, status: :created, location: @sexto }
      else
        format.html { render :new }
        format.json { render json: @sexto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sextos/1
  # PATCH/PUT /sextos/1.json
  def update
    respond_to do |format|
      if @sexto.update(sexto_params)
        format.html { redirect_to @sexto, notice: 'Sexto was successfully updated.' }
        format.json { render :show, status: :ok, location: @sexto }
      else
        format.html { render :edit }
        format.json { render json: @sexto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sextos/1
  # DELETE /sextos/1.json
  def destroy
    @sexto.destroy
    respond_to do |format|
      format.html { redirect_to sextos_url, notice: 'Sexto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sexto
      @sexto = Sexto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sexto_params
      params.require(:sexto).permit(:name, :bio, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sextos_helper.rb
module SextosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zombie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sextos/_form.html.erb
<%= form_for(sexto) do |f| %>
  <% if sexto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sexto.errors.count, "error") %> prohibited this sexto from being saved:</h2>

      <ul>
      <% sexto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sextos/edit.html.erb
<h1>Editing Sexto</h1>

<%= render 'form', sexto: @sexto %>

<%= link_to 'Show', @sexto %> |
<%= link_to 'Back', sextos_path %>

app/views/sextos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sextos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sextos.each do |sexto| %>
      <tr>
        <td><%= sexto.name %></td>
        <td><%= sexto.bio %></td>
        <td><%= sexto.age %></td>
        <td><%= link_to 'Show', sexto %></td>
        <td><%= link_to 'Edit', edit_sexto_path(sexto) %></td>
        <td><%= link_to 'Destroy', sexto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sexto', new_sexto_path %>

app/views/sextos/new.html.erb
<h1>New Sexto</h1>

<%= render 'form', sexto: @sexto %>

<%= link_to 'Back', sextos_path %>

app/views/sextos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sexto.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @sexto.bio %>
</p>

<p>
  <strong>Age:</strong>
  <%= @sexto.age %>
</p>

<%= link_to 'Edit', edit_sexto_path(@sexto) %> |
<%= link_to 'Back', sextos_path %>